### ISSUE TITLE
Docker doesn't work

### ISSUE THREAD

**Issue by chrismeyersfsu** [ToucanToco/weaverbird#1035]
## Steps to reproduce
* `docker run --rm --name peanutbutter -p 3000:3000 toucantoco/weaverbird-playground:master` OR `docker run --rm --name peanutbutter -p 3000:3000 toucantoco/weaverbird-playground:release-0.57.0`

## Expected
* http://localhost:3000/?backend=pandas to come up
* To see sample csv data

## Actual
* http://localhost:3000/?backend=pandas comes up
* No sample csv data displayed

## Additional Info
Looking at the docker logs it seems that the python module `weaverbird` isn't installed in the virtual env (logs below).

```
$ /weaverbird/node_modules/.bin/concurrently 'yarn start' 'cd server; FLASK_APP=playground FLASK_RUN_HOST=0.0.0.0 FLASK_RUN_PORT=5000 poetry run flask run'
[0] $ node playground/server.js
[0] [HPM] Proxy created: /pandas-backend  -> http://localhost:5000
[0] [HPM] Proxy rewrite rule created: "^/pandas-backend" ~> ""
[0] (node:52) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
[0] (Use `node --trace-warnings ...` to show where the warning was created)
[0] (node:52) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
[0] (node:52) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
[0] (node:52) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
[0] VQB playground app listening on port 3000!
[1]  * Serving Flask app "playground"
[1]  * Environment: production
[1]    WARNING: This is a development server. Do not use it in a production deployment.
[1]    Use a production WSGI server instead.
[1]  * Debug mode: off
[1] Usage: flask run [OPTIONS]
[1]
[1] Error: While importing "server.playground", an ImportError was raised:
[1]
[1] Traceback (most recent call last):
[1]   File "/root/.cache/pypoetry/virtualenvs/weaverbird-pf-SCsIT-py3.8/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
[1]     __import__(module_name)
[1]   File "/weaverbird/server/playground.py", line 16, in <module>
[1]     from weaverbird.backends.pandas_executor.pipeline_executor import (
[1] ModuleNotFoundError: No module named 'weaverbird'
[1]
[1] cd server; FLASK_APP=playground FLASK_RUN_HOST=0.0.0.0 FLASK_RUN_PORT=5000 poetry run flask run exited with code 2
```

**Comment by davinov** [comment]
Thank you for first contribution @chrismeyersfsu !
And sorry for this mistake ><
